### ISSUE TITLE
join() got an unexpected keyword argument 'aliased'

### ISSUE THREAD

**Issue by ale-reyes** [micahflee/semiphemeral#121]
after importing my tweets from an archive for about five hours I got hit with this message:

Calculating which threads should be excluded
Traceback (most recent call last):
  File "C:\Users\alejandro\AppData\Local\Programs\Python\Python38\Scripts\semiphemeral-script.py", line 33, in <module>
    sys.exit(load_entry_point('semiphemeral==0.7', 'console_scripts', 'semiphemeral')())
  File "c:\users\alejandro\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\alejandro\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "c:\users\alejandro\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\alejandro\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\alejandro\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\alejandro\appdata\local\programs\python\python38\lib\site-packages\semiphemeral\__init__.py", line 74, in delete
    t.delete()
  File "c:\users\alejandro\appdata\local\programs\python\python38\lib\site-packages\semiphemeral\twitter.py", line 299, in delete
    self.fetch()
  File "c:\users\alejandro\appdata\local\programs\python\python38\lib\site-packages\semiphemeral\twitter.py", line 201, in fetch
    self.calculate_excluded_threads()
  File "c:\users\alejandro\appdata\local\programs\python\python38\lib\site-packages\semiphemeral\twitter.py", line 274, in calculate_excluded_threads
    self.common.session.query(Thread)
TypeError: join() got an unexpected keyword argument 'aliased'

also happens if i try using the browser interface at all
(sorry about the formatting, this looks fine when im writing it but after submitting it looks really weird)

**Comment by ale-reyes** [comment]
wait a second this one might be my fault..............

**Comment by ale-reyes** [comment]
ok i think i fixed this? i was trying to fix another error i got when using the "stats" command by downgrading sqlalchemy to version 1.3.10, that worked for that error and seems to also have fixed the one above as well
