### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while getting the str of an object

### ISSUE THREAD

**Issue by weems** [micahflee/semiphemeral#17]
``Traceback (most recent call last):
  File "c:\program files (x86)\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python37-32\Scripts\semiphemeral.exe\__main__.py", line 9, in <module>
  File "c:\program files (x86)\python37-32\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\program files (x86)\python37-32\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\program files (x86)\python37-32\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\program files (x86)\python37-32\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\program files (x86)\python37-32\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\program files (x86)\python37-32\lib\site-packages\semiphemeral\__init__.py", line 53, in fetch
    t.fetch()
  File "c:\program files (x86)\python37-32\lib\site-packages\semiphemeral\twitter.py", line 64, in fetch
    fetched_count += self.import_tweet(Tweet(status))
  File "c:\program files (x86)\python37-32\lib\site-packages\semiphemeral\twitter.py", line 184, in import_tweet
    fetched_count += self.import_tweet(Tweet(status))
  File "c:\program files (x86)\python37-32\lib\site-packages\semiphemeral\twitter.py", line 184, in import_tweet
    fetched_count += self.import_tweet(Tweet(status))
  File "c:\program files (x86)\python37-32\lib\site-packages\semiphemeral\twitter.py", line 184, in import_tweet
    fetched_count += self.import_tweet(Tweet(status))
  [Previous line repeated 941 more times]
  File "c:\program files (x86)\python37-32\lib\site-packages\semiphemeral\twitter.py", line 171, in import_tweet
    if not tweet.already_saved(self.common.session):
  File "c:\program files (x86)\python37-32\lib\site-packages\semiphemeral\db.py", line 76, in already_saved
    tweet = session.query(Tweet).filter_by(status_id=self.status_id).first()
  File "c:\program files (x86)\python37-32\lib\site-packages\sqlalchemy\orm\query.py", line 3221, in first
    ret = list(self[0:1])
  File "c:\program files (x86)\python37-32\lib\site-packages\sqlalchemy\orm\query.py", line 3011, in __getitem__
    return list(res)
  File "c:\program files (x86)\python37-32\lib\site-packages\sqlalchemy\orm\query.py", line 3323, in __iter__
    return self._execute_and_instances(context)
  File "c:\program files (x86)\python37-32\lib\site-packages\sqlalchemy\orm\query.py", line 3348, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "c:\program files (x86)\python37-32\lib\site-packages\sqlalchemy\engine\base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "c:\program files (x86)\python37-32\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "c:\program files (x86)\python37-32\lib\site-packages\sqlalchemy\engine\base.py", line 1098, in _execute_clauseelement
    else None,
  File "<string>", line 1, in <lambda>
  File "c:\program files (x86)\python37-32\lib\site-packages\sqlalchemy\sql\elements.py", line 462, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "c:\program files (x86)\python37-32\lib\site-packages\sqlalchemy\sql\elements.py", line 468, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "c:\program files (x86)\python37-32\lib\site-packages\sqlalchemy\sql\compiler.py", line 562, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "c:\program files (x86)\python37-32\lib\site-packages\sqlalchemy\sql\compiler.py", line 319, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "c:\program files (x86)\python37-32\lib\site-packages\sqlalchemy\sql\compiler.py", line 350, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "c:\program files (x86)\python37-32\lib\site-packages\sqlalchemy\sql\visitors.py", line 91, in _compiler_dispatch
    return meth(self, **kw)
  File "c:\program files (x86)\python37-32\lib\site-packages\sqlalchemy\sql\compiler.py", line 2115, in visit_select
    text, select, inner_columns, froms, byfrom, kwargs
  File "c:\program files (x86)\python37-32\lib\site-packages\sqlalchemy\sql\compiler.py", line 2214, in _compose_select_body
    t = select._whereclause._compiler_dispatch(self, **kwargs)
  File "c:\program files (x86)\python37-32\lib\site-packages\sqlalchemy\sql\visitors.py", line 91, in _compiler_dispatch
    return meth(self, **kw)
  File "c:\program files (x86)\python37-32\lib\site-packages\sqlalchemy\sql\compiler.py", line 1283, in visit_binary
    return self._generate_generic_binary(binary, opstring, **kw)
  File "c:\program files (x86)\python37-32\lib\site-packages\sqlalchemy\sql\compiler.py", line 1331, in _generate_generic_binary
    self, eager_grouping=eager_grouping, **kw
  File "c:\program files (x86)\python37-32\lib\site-packages\sqlalchemy\sql\visitors.py", line 91, in _compiler_dispatch
    return meth(self, **kw)
  File "c:\program files (x86)\python37-32\lib\site-packages\sqlalchemy\sql\compiler.py", line 1476, in visit_bindparam
    name = self._truncate_bindparam(bindparam)
  File "c:\program files (x86)\python37-32\lib\site-packages\sqlalchemy\sql\compiler.py", line 1535, in _truncate_bindparam
    bind_name = self._truncated_identifier("bindparam", bind_name)
  File "c:\program files (x86)\python37-32\lib\site-packages\sqlalchemy\sql\compiler.py", line 1546, in _truncated_identifier
    anonname = name.apply_map(self.anon_map)
  File "c:\program files (x86)\python37-32\lib\site-packages\sqlalchemy\sql\elements.py", line 4302, in apply_map
    return self % map_
  File "c:\program files (x86)\python37-32\lib\site-packages\sqlalchemy\util\_collections.py", line 734, in __missing__
    self[key] = val = self.creator(key)
  File "c:\program files (x86)\python37-32\lib\site-packages\sqlalchemy\sql\compiler.py", line 1568, in _process_anon
    return derived + "_" + str(anonymous_counter)
RecursionError: maximum recursion depth exceeded while getting the str of an object``

fetch operation failed in process due to a RecursionLimit

**Comment by dcdb16** [comment]
Hey. I was able to correct this by opening 'twitter.py' and adding the following lines:

```
import sys
sys.setrecursionlimit(2500)
```
Hasn't broken anything and has gotten the script to run.

**Comment by kees** [comment]
Whoa. I can't reproduce this. Is this still a problem with the latest git version, please open a new issue. Thanks!
