### ISSUE TITLE
semiphemeral on Linux terminal error

### ISSUE THREAD

**Issue by thejoker3000** [micahflee/semiphemeral#68]
After running pip3 install semiphemeral, I try to run it but get the following error. Not sure what is going on. Tweepy is already installed also for if that was going to be a question.
Running on manjaro.

> [thejoker@gibson ~]$ semiphemeral configure
> Traceback (most recent call last):
>   File "/home/thejoker/.local/bin/semiphemeral", line 5, in <module>
>     from semiphemeral import main
>   File "/home/thejoker/.local/lib/python3.8/site-packages/semiphemeral/__init__.py", line 8, in <module>
>     from .web import create_app
>   File "/home/thejoker/.local/lib/python3.8/site-packages/semiphemeral/web.py", line 6, in <module>
>     from .twitter import Twitter
>   File "/home/thejoker/.local/lib/python3.8/site-packages/semiphemeral/twitter.py", line 1, in <module>
>     import tweepy
>   File "/home/thejoker/.local/lib/python3.8/site-packages/tweepy/__init__.py", line 17, in <module>
>     from tweepy.streaming import Stream, StreamListener
>   File "/home/thejoker/.local/lib/python3.8/site-packages/tweepy/streaming.py", line 358
>     def _start(self, async):
>                      ^
> SyntaxError: invalid syntax
> [thejoker@gibson ~]$

**Comment by thejoker3000** [comment]
Wait, I just installed as root and it works fine. Does this have to be executed with sudo permissions?
