### ISSUE TITLE
Not sure what I have done wrong when trying to unlike

### ISSUE THREAD

**Issue by jonasaaay** [micahflee/semiphemeral#75]
I have got the like.js as required, it isn't the SQL error that was reported in another thread and using a shorter file doesn't seem to work either

Am I missing some files? Thanks

error:

semiphemeral 0.6
Traceback (most recent call last):
  File "c:\users\antho\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\antho\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\antho\AppData\Local\Programs\Python\Python39\Scripts\semiphemeral.exe\__main__.py", line 7, in <module>
  File "c:\users\antho\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\antho\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\antho\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\antho\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\antho\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\antho\appdata\local\programs\python\python39\lib\site-packages\semiphemeral\__init__.py", line 87, in unlike
    t.unlike(filename)
  File "c:\users\antho\appdata\local\programs\python\python39\lib\site-packages\semiphemeral\twitter.py", line 466, in unlike
    js_string = f.read()
  File "c:\users\antho\appdata\local\programs\python\python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2931: character maps to <undefined>

**Comment by jonasaaay** [comment]
it worked after saving another file with ANSI encoding... hmmm...
