### ISSUE TITLE
unexpected keyword argument 'wait_on_rate_limit_notify'

### ISSUE THREAD

**Issue by soulflowing** [micahflee/semiphemeral#84]
My system - 

```
 lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```

When running - 

```
$ semiphemeral fetch
semiphemeral 0.6
Traceback (most recent call last):
  File "/home/rollingherenow/.local/bin/semiphemeral", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/rollingherenow/.local/lib/python3.8/site-packages/semiphemeral/__init__.py", line 57, in fetch
    t = Twitter(common)
  File "/home/rollingherenow/.local/lib/python3.8/site-packages/semiphemeral/twitter.py", line 31, in __init__
    self.api = tweepy.API(
TypeError: __init__() got an unexpected keyword argument 'wait_on_rate_limit_notify'
```

I checked these suggested fixes - 

https://stackoverflow.com/questions/37248958/tweepy-wait-on-rate-limit-not-working

https://stackoverflow.com/questions/54846073/unexpected-error-argument-wait-limit-on-a-tweepy-python-script

```
$ pip show tweepy
Name: tweepy
Version: 4.0.0
Summary: Twitter library for Python
Home-page: https://www.tweepy.org/
Author: Joshua Roesslein
Author-email: tweepy@googlegroups.com
License: MIT
Location: /home/[MYUSER]/.local/lib/python3.8/site-packages
Requires: requests-oauthlib, requests
Required-by: semiphemeral
```

Neither of which seem to be the issue.

Please advise, thank you!

**Comment by JacksonChen666** [comment]
reinstalling tweepy to a version that's <4.0.0 works just fine for me. i used version 3.10.0 for tweepy.

**Comment by soulflowing** [comment]
Thanks, Tweepy v3.10.0 worked for me too.

**Comment by dinomite** [comment]
For the other non-Python folks in the audience: `pip3 install tweepy==3.10.0`
