### ISSUE TITLE
Doesn't work without adding user ID to the settings.json file and TypeError in __init__()

### ISSUE THREAD

**Issue by dredstrauss** [micahflee/semiphemeral#93]
When I try to save the settings from the browser, the program crashes. After that, I add my Twitter ID to the settings file and it works. But after that, when I run semiphemeral fetch, this is thrown to the terminal:

```
semiphemeral 0.7
Traceback (most recent call last):
  File "/home/my_username/.local/bin/semiphemeral", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/my_username/.local/lib/python3.7/site-packages/semiphemeral/__init__.py", line 61, in fetch
    t = Twitter(common)
  File "/home/my_username/.local/lib/python3.7/site-packages/semiphemeral/twitter.py", line 34, in __init__
    auth, wait_on_rate_limit=True, wait_on_rate_limit_notify=True, proxy=proxy
TypeError: __init__() got an unexpected keyword argument 'wait_on_rate_limit_notify'
```

Just to try something, I deleted that argument and this was thrown instead:

```
semiphemeral 0.7
Traceback (most recent call last):
  File "/home/my_username/.local/bin/semiphemeral", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/my_username/.local/lib/python3.7/site-packages/semiphemeral/__init__.py", line 61, in fetch
    t = Twitter(common)
  File "/home/my_username/.local/lib/python3.7/site-packages/semiphemeral/twitter.py", line 40, in __init__
    user = self.api.get_user(self.common.settings.get("username"))
  File "/home/my_username/.local/lib/python3.7/site-packages/tweepy/api.py", line 46, in wrapper
    return method(*args, **kwargs)
TypeError: get_user() takes 1 positional argument but 2 were given
```
I know I probably shouldn't go around deleting pieces of code and hoping it works, but maybe that other message helps? I'm not sure how should I help with this one (I'm just starting to learn some basic coding).

I'm using Linux Mint Debian Edition 4 "Debbie" with the 4.19.0-18-amd64 kernel and pip3 installed the 0.7 version of semiphemeral

**Comment by kees** [comment]
What version of Tweepy do you have installed?

**Comment by dredstrauss** [comment]
> What version of Tweepy do you have installed?

I just checked: 4.4.0

**Comment by kees** [comment]
That'll do it. :) semiphemeral only works with Tweepy 3.10.x (see bug #92 )
