### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Mahh0** [micahflee/semiphemeral#98]
Hello, I'm trying to configure semiphemeral on my raspberry, but I got the following error after saving configuration; it happens when I put something in username
```
127.0.0.1 - - [08/Jan/2022 17:41:00] "POST /settings HTTP/1.1" 500 -
[2022-01-08 17:42:08,523] ERROR in app: Exception on /api/statistics [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/.local/lib/python3.9/site-packages/semiphemeral/web.py", line 149, in api_statistics
    return jsonify(common.get_stats())
  File "/home/pi/.local/lib/python3.9/site-packages/semiphemeral/common.py", line 33, in get_stats
    int(self.settings.get("user_id"))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by juju4** [comment]
same here

```
 * Debug mode: off
 * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
127.0.0.1 - - [09/Jan/2022 11:56:34] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [09/Jan/2022 11:56:34] "GET /settings HTTP/1.1" 200 -
127.0.0.1 - - [09/Jan/2022 11:56:34] "GET /static/style.css HTTP/1.1" 200 -
127.0.0.1 - - [09/Jan/2022 11:56:34] "GET /static/js/lib/jquery-3.4.1.min.js HTTP/1.1" 200 -
127.0.0.1 - - [09/Jan/2022 11:56:34] "GET /static/js/base.js HTTP/1.1" 200 -
127.0.0.1 - - [09/Jan/2022 11:56:35] "GET /static/js/settings.js HTTP/1.1" 200 -
127.0.0.1 - - [09/Jan/2022 11:56:35] "GET /api/statistics HTTP/1.1" 200 -
127.0.0.1 - - [09/Jan/2022 11:56:35] "GET /favicon.ico HTTP/1.1" 404 -
[2022-01-09 11:59:21,609] ERROR in app: Exception on /settings [POST]
Traceback (most recent call last):
  File "/home/pi/tmp/venv-semiphemeral/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/tmp/venv-semiphemeral/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/tmp/venv-semiphemeral/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/tmp/venv-semiphemeral/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/pi/tmp/venv-semiphemeral/lib/python3.7/site-packages/semiphemeral/web.py", line 106, in edit_settings
    twitter = Twitter(common)
  File "/home/pi/tmp/venv-semiphemeral/lib/python3.7/site-packages/semiphemeral/twitter.py", line 34, in __init__
    auth, wait_on_rate_limit=True, wait_on_rate_limit_notify=True, proxy=proxy
TypeError: __init__() got an unexpected keyword argument 'wait_on_rate_limit_notify'
127.0.0.1 - - [09/Jan/2022 11:59:21] "POST /settings HTTP/1.1" 500 -
[2022-01-09 11:59:46,972] ERROR in app: Exception on /api/statistics [GET]
Traceback (most recent call last):
  File "/home/pi/tmp/venv-semiphemeral/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/tmp/venv-semiphemeral/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/tmp/venv-semiphemeral/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/tmp/venv-semiphemeral/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/pi/tmp/venv-semiphemeral/lib/python3.7/site-packages/semiphemeral/web.py", line 149, in api_statistics
    return jsonify(common.get_stats())
  File "/home/pi/tmp/venv-semiphemeral/lib/python3.7/site-packages/semiphemeral/common.py", line 33, in get_stats
    int(self.settings.get("user_id"))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

install setup with python3 in a venv.

**Comment by teisseire117** [comment]
I have same issue ! I tried re-installing but it doesn't work :/

**Comment by Mahh0** [comment]
Mb you just need to downgrade tweepy version ( pip install --upgrade tweepy==[older_version]
